### ISSUE TITLE
Troubles installing / Task feedback

### ISSUE THREAD

**Issue by at0g** [JamieMason/grunt-imageoptim#14]
It took me a long time to get this package working. Perhaps I'm just stupid.

Could you possibly update the readme with clear installation steps, or update the grunt task to provide some meaningful feedback.

Here's a rundown of how my setup went:

npm install -g imageoptim-cli
npm install grunt-imageoptim

Try to run, get an error that tells me nothing, except something is wrong. 
At this point I did not know I needed to install imageoptim.

Go to the imageoptim website, install imageoptim on my lion machine.
Try to run the task. Get the same error that tells me nothing.
Eventually read more on the imageoptim homepage and learn I must explicitly enable the app to run, because I'm on mountain lion and gatekeeper is ruining my mojo.

Run the imageoptim task again, with imagealpha and jpegmini set to false.
Something happens.

Set imagealpha to true in the task options. Try to run the task. Another fail. Same useless error message.
Refer to the readme on the imageoptim page. Install imagealpha. Repeat the same steps to circumvent gatekeeper.

Run the task again. Now it works.

Update the task options and set jpegmini to true. Download jpegmini trial/light.
Task won't run. 

Spend $30 buying jpegmini.
Try to run the task, still won't work, still the same error message. 
Mess around uninstalling jpegmini light, as the in-app upgrade as left the app named jpegmini-light. Maybe this is the cause of the error?

Try to run the task again, same old error message.

I'm really frustrated at this point, not only have I wasted a lot of time, I've also spent $30 in the app store to get jpegmini to use with this task and it won't run.

Next up, I try imageoptim CLI directly, perhaps it will provide me with useful feedback if it fails.

When I try to run the imageoptim task, I get a useful error message. 
I need to enable access for assistive devices. Ok. Easy. Done.

Try the CLI task. Works. Try the grunt task, it finally works.

It would have been really helpful if the grunt task had printed the message about assistive devices, or really any meaningful feedback about the numerous errors.

Failing that, could you please update the readme so the dependencies and additional steps (installing additional apps, allowing software to run & enabling access for assistive devices) are displayed upfront.

**Comment by JamieMason** [comment]
Sorry for the huge wait, I will close this and instead track ongoing issues over at https://github.com/JamieMason/ImageOptim-CLI/.
