### ISSUE TITLE
Fails when processing very large folders

### ISSUE THREAD

**Issue by nwtn** [JamieMason/grunt-imageoptim#19]
I'm getting this error when running grunt-imageoptim on a directory containing a large number of images. This does not happen with smaller directories. ImageOptim (the GUI app) runs fine (though slowly) and processes all the files. The error shows up in the Terminal while grunt-imageoptim's output is being printed.

In the output below, I'm running `ImageAlpha`, `JPEGmini`, and `ImageOptim`, but the error happens even with `ImageOptim` alone. With the output below it dies after 1102 files, but sometimes it's a little more or less.

```
Running "imageoptim:blamo" (imageoptim) task...
Running ImageAlpha......
Running JPEGmini......
Running ImageOptim......
....png was: 44.035kb now: 43.362kb saving: .673kb (1.00%) quality: 99.9825827%
....png was: 44.119kb now: 60.439kb saving: -16.320kb (-36.00%) quality: %
....png was: 113.611kb now: 113.611kb saving: 0kb (0%) quality: 100%
...snip...
....jpg was: 29.078kb now: 29.078kb saving: 0kb (0%) quality: 100%
....jpg was: 44.367kb now: 44.367kb saving: 0kb (0%) quality: 100%
Fatal error: ImageOptim-CLI exited with a failure status...
```

**Comment by JamieMason** [comment]
Sorry for the huge wait, I will close this and instead track ongoing issues over at https://github.com/JamieMason/ImageOptim-CLI/.
