### ISSUE TITLE
3.6hours later.... nothing was written

### ISSUE THREAD

**Issue by intellix** [JamieMason/grunt-imageoptim#20]
Was just using this tool to minify everything and see that after 3.6 hours of 100% CPU, it says that it exited with a failure status:

``` bash
/Users/wats/Sites/grunt/src/c/6/48/2h1.png was: 220.211kb now: 69.160kb saving: 151.051kb (68.00%)
/Users/wats/Sites/grunt/src/c/6/48/2h2.png was: 221.880kb now: 70.385kb saving: 151.495kb (68.00%)
/Users/wats/Sites/grunt/src/c/6/48/2h3.png was: 217.723kb now: 69.171kb saving: 148.552kb (68.00%)
/Users/wats/Sites/grunt/src/c/6/48/3h1.png was: 219.652kb now: 68.416kb saving: 151.236kb (68.00%)
/Users/wats/Sites/grunt/src/c/6/48/3h2.png was: 221.311kb now: 69.982kb saving: 151.329kb (68.00%)
/Users/wats/Sites/grunt/src/c/6/48/3h3.png was: 217.078kb now: 69.435kb saving: 147.643kb (68.00%)
Fatal error: ImageOptim-CLI exited with a failure status
```

I check out the files and it seems that they're all the same size :(
I guess ImageOptim is incredibly slow and intensive and for PNGs it doesn't seem to save THAT much in comparison to ImageAlpha which runs much quicker. Perhaps it would be a good idea to disable ImageOptim and just use Alpha?
Optim says it saved me about 12% average, but Alpha saved about 60-80%

Thanks!

**Comment by JamieMason** [comment]
Sorry for the huge wait, I will close this and instead track ongoing issues over at https://github.com/JamieMason/ImageOptim-CLI/.
