### ISSUE TITLE
New version of imageoptim-cli breaks Jpegmini functionality

### ISSUE THREAD

**Issue by maxwellhibbert** [JamieMason/grunt-imageoptim#29]
I just started a new project and Jpegmini via grunt-imageoptim wouldn't work for me the way it usually does. It just hangs while trying to open the temp files.
I compared the grunt-imageoptim install against an older one that's still working fine and noticed that imageoptim-cli is was a couple of versions ahead 1.7.11 -> 1.11.4. Replacing the new version with the old fixed the issue, so something in either 1.11.3 or 1.11.4 of imageoptim-cli broke jpegmini in grunt-imageoptim.
Also, thanks for this plugin, it saves me a bunch of time.

**Comment by sliday** [comment]
I tried rolling back to 1.7.11 and 1.7.1, unfortunately that did not help. I miss JPEGMini integration.

**Comment by JamieMason** [comment]
Sorry for the huge wait, 1.4.2 has been released which has some small updates to npm dependencies. Given the time that has passed, I will close this and instead track ongoing issues over at https://github.com/JamieMason/ImageOptim-CLI/.
