### ISSUE TITLE
Imageoptim opening gui

### ISSUE THREAD

**Issue by Gouvi** [JamieMason/grunt-imageoptim#30]
So when running my grunt task it is successfully opening and closing imagealpha but when it comes to running imageoptim it is opening the gui applicaion. Now this would take hours and crash it on some occassions. What I found was that if I close the gui application the grunt task would continue to execute successfully compressing images on average by around 70%.

The grunt task has been setup as followed:
``imageoptim: {

```
        files: {

            options: {

                imageAlpha: true,

                jpegMini: false,

                quitAfter: true

            },

            src: ['src/']

        },

    }``
```

Is it natural for the gui to open or have I stuffed up a step in the installation/setup?

Thanks for your help!

**Comment by JamieMason** [comment]
Sorry for the huge wait, I will close this and instead track ongoing issues over at https://github.com/JamieMason/ImageOptim-CLI/.
