### ISSUE TITLE
ImageAlpha doesn't appear to be running

### ISSUE THREAD

**Issue by JayCarney** [JamieMason/grunt-imageoptim#32]
When i run via grunt I'm getting a `Running ImageAlpha...` message, but the images don't appear to be optimised via ImageAlpha, if I open ImageAlpha and manually run it; I'm getting final image sizes 25% of that I'm getting from running `grunt imageoptim`. I have version 1.3.5 of ImageAlpha installed.

```
imageoptim: {
      options: {
        jpegMini: false,
        imageAlpha: false,
        quitAfter: true
      }
      png: {
        options: {
          imageAlpha: true
        },
        src: [
          'static/img/**/*.png',
          'uploads/**/*.png'
        ]
      }
}
```

**Comment by natelandau** [comment]
same issue here.

**Comment by JamieMason** [comment]
Thank you for reporting this, it is being tracked in https://github.com/JamieMason/ImageOptim-CLI/issues/68.
