### ISSUE TITLE
Problem with Grunt

### ISSUE THREAD

**Issue by cozy2963** [JamieMason/grunt-imageoptim#34]
Everytime that I try to install and use with grunt, I am getting a message about minimatch: 
deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

And: npm WARN grunt-imageoptim@1.4.1 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-contrib-jshint@0.6.5 requires a peer of grunt@~0.4.0 but none was installed.

Any help would be appreciated. I have scoured the internet and tried various things. Thanks.

**Comment by JamieMason** [comment]
Hi @cozy2963, I've updated the npm dependencies and released 1.4.2 which should hopefully fix this deprecation notice.

**Comment by cozy2963** [comment]
Thank you Jamie! It worked.
